// Import types and fonts from Next.js
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";

// Import global CSS
import "./globals.css";

// Load Geist Sans font and assign it to a CSS variable
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

// Load Geist Mono font and assign it to a CSS variable
const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// Metadata for the HTML document (used by Next.js for SEO and document head)
export const metadata: Metadata = {
  title: "Create Next App", // Page title
  description: "Generated by create next app", // Page description
};

// Root layout component that wraps all pages
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode; // Any child components (pages) rendered inside this layout
}>) {
  return (
    <html lang="en">
      <head>
        {/* RippleUI styles for UI components */}
        <link
          href="https://cdn.jsdelivr.net/npm/rippleui@1.12.1/dist/css/styles.css"
          rel="stylesheet"
        />
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {/* Render all child components (pages) here */}
        {children}
      </body>
    </html>
  );
}
